language: php

php:
  - 7.1

env:
  - DB=mysql
 
before_script:
  - cp .env.example .env
  - composer install
  - php artisan key:generate
  - mysql -e 'CREATE DATABASE homestead;'

script:
  - vendor/bin/phpunit
  - php artisan migrate
